public enum AppStringKey: String, CaseIterable, Sendable {
  case aboutCredits
  case aboutRazerMacOS
  case appBuildDescription
  case appTitle
  case battery
  case batteryMenu
  case batteryStatusUnavailable
  case bridgeCommandSent
  case bridgeConnected
  case bridgeDetectedReadTimedOut
  case bridgeReadyForBridge
  case capabilityBattery
  case capabilityDPI
  case capabilityDiscovery
  case capabilityLighting
  case capabilityPollingRate
  case capabilityProfiles
  case charging
  case connection
  case connectionLibrazermacosInternal
  case connectionUSBReceiverWired
  case connectedDevices
  case controlsPreviewHardwareNotMatched
  case couldNotApplyAction
  case device
  case deviceBridge
  case deviceControls
  case deviceStatus
  case devices
  case detailSubtitle
  case dpiMenu
  case general
  case hardwareNoConnectedMouse
  case hardwareRejectedDPI
  case hardwareRejectedPollingRate
  case language
  case lastUpdate
  case launchAtLogin
  case launchAtLoginDisabledMessage
  case launchAtLoginEnabledMessage
  case launchAtLoginHelp
  case launchAtLoginStatus
  case lighting
  case lightingApplyColor
  case lightingApplyEffect
  case lightingBlue
  case lightingBrightness
  case lightingEffect
  case lightingGreen
  case lightingPreviewOnly
  case lightingRed
  case lightingStaticColor
  case lightingUnavailable
  case legacyProfileLoaded
  case liveMouseLoaded
  case noDeviceSelected
  case noConnectedDevices
  case noRazerMouse
  case noSupportedDisconnectedDevices
  case openLoginItemsSettings
  case openRazerMacOS
  case pollingRate
  case previewedAction
  case productID
  case quit
  case rateMenu
  case razerDevice
  case readyToBridge
  case refresh
  case refreshDevices
  case runtime
  case savePollingRate
  case searchDevices
  case sentAction
  case setDPI
  case settings
  case signing
  case signingPlanned
  case status
  case statusBar
  case statusBarAlwaysOn
  case statusDisabled
  case statusEnabled
  case statusRequiresApproval
  case statusUnavailable
  case statusUnknown
  case supportedDisconnectedDevices
  case targetLoadedNoLiveMouse
}
