extension AppText {
  static let english: [AppStringKey: String] = [
    .aboutCredits: """
    Native SwiftUI/AppKit control app for Razer devices on macOS.

    Current native surface:
    - Menu-bar resident app
    - Launch at Login
    - Legacy device catalog loaded in Swift
    - Keyboard, mouse, mouse mat, dock, eGPU, headphone, and accessory profiles
    - Lighting-effect, RGB, and brightness controls in native preview
    - DPI and polling-rate writes through librazermacos for matched mice
    - Hardware status with conservative timeout reporting

    Lighting writes remain preview-only until the native bridge exposes and verifies the matching librazermacos endpoints for each device family.

    Built on 1kc/razer-macos, librazermacos, and OpenRazer device work.
    """,
    .aboutRazerMacOS: "About Razer macOS",
    .appBuildDescription: "SwiftUI/AppKit + librazermacos bridge",
    .appTitle: "Razer macOS Native",
    .battery: "Battery",
    .batteryMenu: "Battery: %d%%",
    .batteryStatusUnavailable: "Battery status unavailable from the current bridge read.",
    .bridgeCommandSent: "Command sent through librazermacos bridge.",
    .bridgeConnected: "Connected through librazermacos bridge.",
    .bridgeDetectedReadTimedOut: "Detected through librazermacos; settings read timed out.",
    .bridgeReadyForBridge: "Ready for librazermacos bridge.",
    .capabilityBattery: "Battery",
    .capabilityDPI: "DPI",
    .capabilityDiscovery: "USB discovery",
    .capabilityLighting: "Lighting effects",
    .capabilityPollingRate: "Polling rate",
    .capabilityProfiles: "Profiles",
    .charging: "Charging",
    .connection: "Connection",
    .connectionLibrazermacosInternal: "librazermacos internal #%@",
    .connectionUSBReceiverWired: "USB receiver / wired",
    .connectedDevices: "Connected devices",
    .controlsPreviewHardwareNotMatched: "Controls available in preview; hardware not matched.",
    .couldNotApplyAction: "Could not apply %@",
    .device: "Device",
    .deviceBridge: "Device bridge",
    .deviceControls: "Device controls",
    .deviceStatus: "Device status",
    .devices: "Devices",
    .detailSubtitle: "Adjust device settings and review the current hardware connection.",
    .dpiMenu: "DPI: %d",
    .general: "General",
    .hardwareNoConnectedMouse: "No connected librazermacos mouse matched this device.",
    .hardwareRejectedDPI: "librazermacos rejected DPI update.",
    .hardwareRejectedPollingRate: "librazermacos rejected polling-rate update.",
    .language: "Language",
    .lastUpdate: "Last update",
    .launchAtLogin: "Launch at Login",
    .launchAtLoginDisabledMessage: "Launch at Login is disabled.",
    .launchAtLoginEnabledMessage: "Launch at Login is enabled.",
    .launchAtLoginHelp: "Launch at Login is registered with macOS ServiceManagement. If the local unsigned build shows Requires approval or Unavailable, check System Settings > General > Login Items.",
    .launchAtLoginStatus: "Launch at Login status",
    .lighting: "Lighting",
    .lightingApplyColor: "Apply Color",
    .lightingApplyEffect: "Apply Effect",
    .lightingBlue: "Blue",
    .lightingBrightness: "Brightness",
    .lightingEffect: "Effect",
    .lightingGreen: "Green",
    .lightingPreviewOnly: "Lighting changes are preview-only until the native bridge exposes lighting writes for this device.",
    .lightingRed: "Red",
    .lightingStaticColor: "Static color",
    .lightingUnavailable: "This device profile does not expose lighting controls.",
    .legacyProfileLoaded: "Legacy device profile loaded; hardware writes depend on native bridge support.",
    .liveMouseLoaded: "Live Razer devices loaded: %d",
    .noDeviceSelected: "No device selected",
    .noConnectedDevices: "No connected Razer devices detected",
    .noRazerMouse: "No Razer device",
    .noSupportedDisconnectedDevices: "No supported devices match",
    .openLoginItemsSettings: "Open Login Items in System Settings",
    .openRazerMacOS: "Open Razer macOS",
    .pollingRate: "Polling rate",
    .previewedAction: "Previewed %@; hardware not matched",
    .productID: "Product ID",
    .quit: "Quit",
    .rateMenu: "Rate: %d Hz",
    .razerDevice: "Razer device",
    .readyToBridge: "Ready to bridge %@",
    .refresh: "Refresh",
    .refreshDevices: "Refresh Devices",
    .runtime: "Runtime",
    .savePollingRate: "Save Polling Rate",
    .searchDevices: "Search devices",
    .sentAction: "Sent %@ to hardware",
    .setDPI: "Set DPI",
    .settings: "Settings",
    .signing: "Signing",
    .signingPlanned: "Planned",
    .status: "Status",
    .statusBar: "Status bar",
    .statusBarAlwaysOn: "Always on",
    .statusDisabled: "Disabled",
    .statusEnabled: "Enabled",
    .statusRequiresApproval: "Requires approval",
    .statusUnavailable: "Unavailable",
    .statusUnknown: "Unknown",
    .supportedDisconnectedDevices: "Supported but not connected",
    .targetLoadedNoLiveMouse: "Target devices loaded: %d; no live Razer device matched"
  ]
}
